name = "subscription-notifier"
main = "src/worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# 每5分钟检查一次通知
[triggers]
crons = ["*/10 * * * *"]

# 日志配置
[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true